// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGZ7L9DxDy9HTYt8x_IQdvxcrZ7rI0FQ',
    appId: '1:828180770073:web:14427b568591711ae5e988',
    messagingSenderId: '828180770073',
    projectId: 'finance-app-e0244',
    authDomain: 'finance-app-e0244.firebaseapp.com',
    storageBucket: 'finance-app-e0244.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxb1iiKnyeznqeNftZ1BmeZiiYLbqiYA',
    appId: '1:828180770073:android:4af0ad39cf94cc15e5e988',
    messagingSenderId: '828180770073',
    projectId: 'finance-app-e0244',
    storageBucket: 'finance-app-e0244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDsSm3Fy7-FeE8bWqoU0Kxn9MriddDXp8',
    appId: '1:828180770073:ios:c528b6780251f4ffe5e988',
    messagingSenderId: '828180770073',
    projectId: 'finance-app-e0244',
    storageBucket: 'finance-app-e0244.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );
}
